version: '3'
services:
  router:
    image: frrouting/frr:latest
    container_name: frr-router
    privileged: true
    network_mode: "none"
    volumes:
      - ./frr/router:/etc/frr
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    
  host_a:
    image: frrouting/frr:latest
    container_name: host-a
    network_mode: "none"
    volumes:
      - ./frr/host_a:/etc/frr
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    
  host_b:
    image: frrouting/frr:latest
    container_name: host-b
    network_mode: "none"
    volumes:
      - ./frr/host_b:/etc/frr
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN