  version: '3'
  services:
    core_router:
      image: frrouting/frr:latest
      container_name: core-router
      privileged: true
      networks:
        custom_net1:
          ipv4_address: 10.0.1.2
        custom_net2:
          ipv4_address: 10.0.2.2
        custom_net3:
          ipv4_address: 10.0.3.2
      volumes:
        - ./frr/core_router:/etc/frr
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
      
    router_a:
      image: frrouting/frr:latest
      container_name: router-a
      privileged: true
      networks:
        custom_net1:
          ipv4_address: 10.0.1.1
        custom_net4:
          ipv4_address: 192.168.1.2
      volumes:
        - ./frr/router_a:/etc/frr
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
      
    router_b:
      image: frrouting/frr:latest
      container_name: router-b
      privileged: true
      networks:
        custom_net2:
          ipv4_address: 10.0.2.1
        custom_net5:
          ipv4_address: 192.168.2.2
      volumes:
        - ./frr/router_b:/etc/frr
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
      
    router_c:
      image: frrouting/frr:latest
      container_name: router-c
      privileged: true
      networks:
        custom_net3:
          ipv4_address: 10.0.3.1
        custom_net6:
          ipv4_address: 192.168.3.2
      volumes:
        - ./frr/router_c:/etc/frr
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
      
    host_a:
      image: frrouting/frr:latest
      container_name: host-a
      networks:
        custom_net4:
          ipv4_address: 192.168.1.1
      volumes:
        - ./frr/host_a:/etc/frr
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN

    host_b:
      image: frrouting/frr:latest
      container_name: host-b
      networks:
        custom_net5:
          ipv4_address: 192.168.2.1
      volumes:
        - ./frr/host_b:/etc/frr
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN

    host_c:
      image: frrouting/frr:latest
      container_name: host-c
      networks:
        custom_net6:
          ipv4_address: 192.168.3.1
      volumes:
        - ./frr/host_c:/etc/frr
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN

  networks:
    custom_net1:
      name: custom_net1
      ipam:
        config:
          - subnet: 10.0.1.0/24
            gateway: 10.0.1.254
    custom_net2:
      name: custom_net2
      ipam:
        config:
          - subnet: 10.0.2.0/24
            gateway: 10.0.2.254
    custom_net3:
      name: custom_net3
      ipam:
        config:
          - subnet: 10.0.3.0/24
            gateway: 10.0.3.254
    custom_net4:
      name: custom_net4
      ipam:
        config:
          - subnet: 192.168.1.0/24
            gateway: 192.168.1.254
    custom_net5:
      name: custom_net5
      ipam:
        config:
          - subnet: 192.168.2.0/24
            gateway: 192.168.2.254
    custom_net6:
      name: custom_net6
      ipam:
        config:
          - subnet: 192.168.3.0/24
            gateway: 192.168.3.254
